-- JLPT N5 Noun Import Script

BEGIN TRANSACTION;

INSERT INTO words (word_level, japanese, kana, romaji, english) VALUES
('N5', '赤', 'あか', 'aka', 'red'),
('N5', '秋', 'あき', 'aki', 'autumn'),
('N5', '雨', 'あめ', 'ame', 'rain'),
('N5', '飴', 'あめ', 'ame', 'candy'),
('N5', '姉', 'あね', 'ane', 'older sister'),
('N5', '兄', 'あに', 'ani', 'older brother'),
('N5', '青', 'あお', 'ao', 'blue'),
('N5', '朝', 'あさ', 'asa', 'morning'),
('N5', '朝ご飯', 'あさごはん', 'asagohan', 'breakfast'),
('N5', '明後日', 'あさって', 'asatte', 'day after tomorrow'),
('N5', '足', 'あし', 'ashi', 'foot'),
('N5', '明日', 'あした', 'ashita', 'tomorrow'),
('N5', '頭', 'あたま', 'atama', 'head'),
('N5', '後', 'あと', 'ato', 'behind'),
('N5', '晩ご飯', 'ばんごはん', 'bangohan', 'dinner'),
('N5', '番号', 'ばんごう', 'bangou', 'number'),
('N5', '勉強', 'べんきょう', 'benkyou', 'to study'),
('N5', '帽子', 'ぼうし', 'boushi', 'hat'),
('N5', '文章', 'ぶんしょう', 'bunshou', 'sentence'),
('N5', '豚肉', 'ぶたにく', 'butaniku', 'pork'),
('N5', '病院', 'びょういん', 'byouin', 'hospital'),
('N5', '病気', 'びょうき', 'byouki', 'illness'),
('N5', '茶色', 'ちゃいろ', 'chairo', 'brown'),
('N5', '茶碗', 'ちゃわん', 'chawan', 'rice bowl'),
('N5', '父', 'ちち', 'chichi', 'father'),
('N5', '地下鉄', 'ちかてつ', 'chikatetsu', 'subway'),
('N5', '地図', 'ちず', 'chizu', 'map'),
('N5', '台所', 'だいどころ', 'daidokoro', 'kitchen'),
('N5', '大学', 'だいがく', 'daigaku', 'university'),
('N5', '出口', 'でぐち', 'deguchi', 'exit'),
('N5', '電気', 'でんき', 'denki', 'electricity'),
('N5', '電車', 'でんしゃ', 'densha', 'train'),
('N5', '電話', 'でんわ', 'denwa', 'telephone'),
('N5', 'どなた', 'どなた', 'donata', 'who'),
('N5', '動物', 'どうぶつ', 'doubutsu', 'animal'),
('N5', '土曜日', 'どようび', 'doyoubi', 'Saturday'),
('N5', '絵', 'え', 'e', 'picture'),
('N5', 'ええ', 'ええ', 'ee', 'yes'),
('N5', '映画', 'えいが', 'eiga', 'movie'),
('N5', '映画館', 'えいがかん', 'eigakan', 'cinema'),
('N5', '英語', 'えいご', 'eigo', 'English language'),
('N5', '駅', 'えき', 'eki', 'station'),
('N5', '鉛筆', 'えんぴつ', 'enpitsu', 'pencil'),
('N5', '服', 'ふく', 'fuku', 'clothes'),
('N5', '二人', 'ふたり', 'futari', 'two people'),
('N5', '二つ', 'ふたつ', 'futatsu', 'two'),
('N5', '二日', 'ふつか', 'futsuka', 'the second day of the month'),
('N5', '封筒', 'ふうとう', 'fuutou', 'envelope'),
('N5', '冬', 'ふゆ', 'fuyu', 'winter'),
('N5', '外国', 'がいこく', 'gaikoku', 'foreign country'),
('N5', '外国人', 'がいこくじん', 'gaikokujin', 'foreigner'),
('N5', '学校', 'がっこう', 'gakkou', 'school'),
('N5', '学生', 'がくせい', 'gakusei', 'student'),
('N5', '玄関', 'げんかん', 'genkan', 'entrance'),
('N5', '元気', 'げんき', 'genki', 'lively'),
('N5', '月曜日', 'げつようび', 'getsuyoubi', 'Monday'),
('N5', '銀行', 'ぎんこう', 'ginkou', 'bank'),
('N5', '五', 'ご', 'go', 'five'),
('N5', '午後', 'ごご', 'gogo', 'p.m.'),
('N5', 'ご飯', 'ごはん', 'gohan', 'meal'),
('N5', '午前', 'ごぜん', 'gozen', 'a.m.'),
('N5', '牛肉', 'ぎゅうにく', 'gyuuniku', 'beef'),
('N5', '牛乳', 'ぎゅうにゅう', 'gyuunyuu', 'cow milk'),
('N5', '歯', 'は', 'ha', 'tooth'),
('N5', '八', 'はち', 'hachi', 'eight'),
('N5', '葉書', 'はがき', 'hagaki', 'postcard'),
('N5', '母', 'はは', 'haha', 'mother'),
('N5', 'はい', 'はい', 'hai', 'yes'),
('N5', '灰皿', 'はいざら', 'haizara', 'ashtray'),
('N5', '箱', 'はこ', 'hako', 'box'),
('N5', '半', 'はん', 'han', 'half'),
('N5', '花', 'はな', 'hana', 'flower'),
('N5', '鼻', 'はな', 'hana', 'nose'),
('N5', '話', 'はなし', 'hanashi', 'conversation'),
('N5', '半分', 'はんぶん', 'hanbun', 'half'),
('N5', '晴れ', 'はれ', 'hare', 'clear weather'),
('N5', '春', 'はる', 'haru', 'spring'),
('N5', '箸', 'はし', 'hashi', 'chopsticks'),
('N5', '橋', 'はし', 'hashi', 'bridge'),
('N5', '二十歳', 'はたち', 'hatachi', 'twenty years old'),
('N5', '二十日', 'はつか', 'hatsuka', 'twentieth day of the month'),
('N5', '辺', 'へん', 'hen', 'area'),
('N5', '下手', 'へた', 'heta', 'unskillful'),
('N5', '部屋', 'へや', 'heya', 'room'),
('N5', '左', 'ひだり', 'hidari', 'left'),
('N5', '東', 'ひがし', 'higashi', 'east'),
('N5', '飛行機', 'ひこうき', 'hikouki', 'airplane'),
('N5', '暇', 'ひま', 'hima', 'free time'),
('N5', '昼', 'ひる', 'hiru', 'noon'),
('N5', '昼ご飯', 'ひるごはん', 'hirugohan', 'lunch'),
('N5', '人', 'ひと', 'hito', 'person'),
('N5', '一人', 'ひとり', 'hitori', 'one person'),
('N5', '一つ', 'ひとつ', 'hitotsu', 'one thing'),
('N5', 'ほか', 'ほか', 'hoka', 'other'),
('N5', '本', 'ほん', 'hon', 'book'),
('N5', '本棚', 'ほんだな', 'hondana', 'bookshelf'),
('N5', '本当', 'ほんとう', 'hontou', 'truth'),
('N5', '百', 'ひゃく', 'hyaku', 'hundred'),
('N5', '一', 'いち', 'ichi', 'one'),
('N5', '一番', 'いちばん', 'ichiban', '1st'),
('N5', '一日', 'いちにち', 'ichinichi', 'one day'),
('N5', '家', 'いえ', 'ie', 'house'),
('N5', '池', 'いけ', 'ike', 'pond'),
('N5', '今', 'いま', 'ima', 'now'),
('N5', '意味', 'いみ', 'imi', 'meaning'),
('N5', '妹', 'いもうと', 'imouto', 'younger sister'),
('N5', '犬', 'いぬ', 'inu', 'dog'),
('N5', '入口', 'いりぐち', 'iriguchi', 'entrance'),
('N5', '色', 'いろ', 'iro', 'colour'),
('N5', '医者', 'いしゃ', 'isha', 'doctor'),
('N5', '一緒', 'いっしょ', 'issho', 'together'),
('N5', '椅子', 'いす', 'isu', 'chair'),
('N5', '五日', 'いつか', 'itsuka', 'the fifth day of the month'),
('N5', '五つ', 'いつつ', 'itsutsu', 'five'),
('N5', '嫌', 'いや', 'iya', 'unpleasant'),
('N5', '字引', 'じびき', 'jibiki', 'dictionary'),
('N5', '自動車', 'じどうしゃ', 'jidousha', 'automobile'),
('N5', '時間', 'じかん', 'jikan', 'time'),
('N5', '辞書', 'じしょ', 'jisho', 'dictionary'),
('N5', '自転車', 'じてんしゃ', 'jitensha', 'bicycle'),
('N5', '上手', 'じょうず', 'jouzu', 'skillful'),
('N5', '授業', 'じゅぎょう', 'jugyou', 'lesson'),
('N5', '十', 'じゅう', 'juu', 'ten'),
('N5', 'かばん', 'かばん', 'kaban', 'bag'),
('N5', '花瓶', 'かびん', 'kabin', 'a vase'),
('N5', '角', 'かど', 'kado', 'corner'),
('N5', '鍵', 'かぎ', 'kagi', 'key'),
('N5', '階段', 'かいだん', 'kaidan', 'stairs'),
('N5', '買い物', 'かいもの', 'kaimono', 'shopping'),
('N5', '会社', 'かいしゃ', 'kaisha', 'company'),
('N5', '紙', 'かみ', 'kami', 'paper'),
('N5', '漢字', 'かんじ', 'kanji', 'kanji'),
('N5', '体', 'からだ', 'karada', 'body'),
('N5', '傘', 'かさ', 'kasa', 'umbrella'),
('N5', '方', 'かた', 'kata', 'way of doing something'),
('N5', '家庭', 'かてい', 'katei', 'household'),
('N5', '川', 'かわ', 'kawa', 'river'),
('N5', '火曜日', 'かようび', 'kayoubi', 'Tuesday'),
('N5', '風邪', 'かぜ', 'kaze', 'a cold'),
('N5', '風', 'かぜ', 'kaze', 'wind'),
('N5', '家族', 'かぞく', 'kazoku', 'family'),
('N5', '警官', 'けいかん', 'keikan', 'policeman'),
('N5', '結婚', 'けっこん', 'kekkon', 'marriage'),
('N5', '今朝', 'けさ', 'kesa', 'this morning'),
('N5', '木', 'き', 'ki', 'tree'),
('N5', '昨日', 'きのう', 'kinou', 'yesterday'),
('N5', '金曜日', 'きんようび', 'kinyoubi', 'Friday'),
('N5', '切符', 'きっぷ', 'kippu', 'ticket'),
('N5', '嫌い', 'きらい', 'kirai', 'hate'),
('N5', '喫茶店', 'きっさてん', 'kissaten', 'coffee shop'),
('N5', '北', 'きた', 'kita', 'north'),
('N5', '切手', 'きって', 'kitte', 'postage stamp'),
('N5', 'こっち', 'こっち', 'kocchi', 'this person or way'),
('N5', 'こちら', 'こちら', 'kochira', 'this way'),
('N5', '子供', 'こども', 'kodomo', 'child'),
('N5', '声', 'こえ', 'koe', 'voice'),
('N5', '九日', 'ここのか', 'kokonoka', 'ninth day of the month'),
('N5', '九つ', 'ここのつ', 'kokonotsu', 'nine'),
('N5', '今晩', 'こんばん', 'konban', 'tonight'),
('N5', '今月', 'こんげつ', 'kongetsu', 'this month'),
('N5', '今週', 'こんしゅう', 'konshuu', 'this week'),
('N5', '言葉', 'ことば', 'kotoba', 'word'),
('N5', '今年', 'ことし', 'kotoshi', 'this year'),
('N5', '交番', 'こうばん', 'kouban', 'police box'),
('N5', '紅茶', 'こうちゃ', 'koucha', 'black tea'),
('N5', '公園', 'こうえん', 'kouen', 'park'),
('N5', '交差点', 'こうさてん', 'kousaten', 'intersection'),
('N5', '口', 'くち', 'kuchi', 'mouth'),
('N5', '果物', 'くだもの', 'kudamono', 'fruit'),
('N5', '曇り', 'くもり', 'kumori', 'cloud'),
('N5', '国', 'くに', 'kuni', 'country'),
('N5', '黒', 'くろ', 'kuro', 'black'),
('N5', '車', 'くるま', 'kuruma', 'car'),
('N5', '薬', 'くすり', 'kusuri', 'medicine'),
('N5', '靴', 'くつ', 'kutsu', 'shoes'),
('N5', '靴下', 'くつした', 'kutsushita', 'socks'),
('N5', '去年', 'きょねん', 'kyonen', 'last year'),
('N5', '今日', 'きょう', 'kyou', 'today'),
('N5', '兄弟', 'きょうだい', 'kyoudai', 'siblings'),
('N5', '教室', 'きょうしつ', 'kyoushitsu', 'classroom'),
('N5', '九', 'きゅう', 'kyuu', 'nine'),
('N5', '町', 'まち', 'machi', 'town'),
('N5', '窓', 'まど', 'mado', 'window'),
('N5', '前', 'まえ', 'mae', 'previous'),
('N5', '毎朝', 'まいあさ', 'maiasa', 'every morning'),
('N5', '毎晩', 'まいばん', 'maiban', 'every night'),
('N5', '毎日', 'まいにち', 'mainichi', 'every day'),
('N5', '毎週', 'まいしゅう', 'maishuu', 'every week'),
('N5', '毎年', 'まいとし', 'maitoshi', 'every year'),
('N5', '毎月', 'まいつき', 'maitsuki', 'every month'),
('N5', '万', 'まん', 'man', 'ten thousand'),
('N5', '万年筆', 'まんねんひつ', 'mannenhitsu', 'fountain pen'),
('N5', '目', 'め', 'me', 'eye'),
('N5', '眼鏡', 'めがね', 'megane', 'glasses'),
('N5', '道', 'みち', 'michi', 'road'),
('N5', '緑', 'みどり', 'midori', 'green'),
('N5', '右', 'みぎ', 'migi', 'right'),
('N5', '三日', 'みっか', 'mikka', 'the third day of the month'),
('N5', '耳', 'みみ', 'mimi', 'ear'),
('N5', '南', 'みなみ', 'minami', 'south'),
('N5', '皆さん', 'みなさん', 'minasan', 'everyone'),
('N5', 'みんな', 'みんな', 'minna', 'all'),
('N5', '店', 'みせ', 'mise', 'shop'),
('N5', '三つ', 'みつ', 'mitsu', 'three'),
('N5', '水', 'みず', 'mizu', 'water'),
('N5', '木曜日', 'もくようび', 'mokuyoubi', 'Thursday'),
('N5', '門', 'もん', 'mon', 'gate'),
('N5', '問題', 'もんだい', 'mondai', 'problem'),
('N5', '物', 'もの', 'mono', 'thing'),
('N5', '六日', 'むいか', 'muika', 'sixth day of the month'),
('N5', '向こう', 'むこう', 'mukou', 'over there'),
('N5', '村', 'むら', 'mura', 'village'),
('N5', '六つ', 'むっつ', 'muttsu', 'six'),
('N5', '中', 'なか', 'naka', 'inside'),
('N5', '名前', 'なまえ', 'namae', 'name'),
('N5', '七つ', 'ななつ', 'nanatsu', 'seven'),
('N5', '七日', 'なのか', 'nanoka', 'seventh day of the month'),
('N5', '夏', 'なつ', 'natsu', 'summer'),
('N5', '夏休み', 'なつやすみ', 'natsuyasumi', 'summer holiday'),
('N5', '猫', 'ねこ', 'neko', 'cat'),
('N5', '二', 'に', 'ni', 'two'),
('N5', '日曜日', 'にちようび', 'nichiyoubi', 'Sunday'),
('N5', '日記', 'にっき', 'nikki', 'diary'),
('N5', '肉', 'にく', 'niku', 'meat'),
('N5', '荷物', 'にもつ', 'nimotsu', 'luggage'),
('N5', '西', 'にし', 'nishi', 'west'),
('N5', '庭', 'にわ', 'niwa', 'garden'),
('N5', '飲み物', 'のみもの', 'nomimono', 'drink'),
('N5', 'おばあさん', 'おばあさん', 'obaasan', 'grandmother'),
('N5', '伯母さん', 'おばさん', 'obasan', 'aunt'),
('N5', 'お弁当', 'おべんとう', 'obentou', 'lunch box'),
('N5', 'お茶', 'おちゃ', 'ocha', 'tea'),
('N5', 'お風呂', 'おふろ', 'ofuro', 'bath'),
('N5', '伯父さん', 'おじさん', 'ojisan', 'uncle'),
('N5', 'お母さん', 'おかあさん', 'okaasan', 'mother'),
('N5', 'お金', 'おかね', 'okane', 'money'),
('N5', 'お菓子', 'おかし', 'okashi', 'candy'),
('N5', '奥さん', 'おくさん', 'okusan', 'wife'),
('N5', 'お巡りさん', 'おまわりさん', 'omawari san', 'police officer'),
('N5', 'お腹', 'おなか', 'onaka', 'stomach'),
('N5', 'お姉さん', 'おねえさん', 'oneesan', 'older sister'),
('N5', '音楽', 'おんがく', 'ongaku', 'music'),
('N5', 'お兄さん', 'おにいさん', 'oniisan', 'older brother'),
('N5', '女', 'おんな', 'onna', 'woman'),
('N5', '女の子', 'おんなのこ', 'onnanoko', 'girl'),
('N5', '大勢', 'おおぜい', 'oozei', 'crowd of people'),
('N5', 'お酒', 'おさけ', 'osake', 'alcohol'),
('N5', 'お皿', 'おさら', 'osara', 'plate'),
('N5', 'お手洗い', 'おてあらい', 'otearai', 'toilet'),
('N5', '男', 'おとこ', 'otoko', 'man'),
('N5', '男の子', 'おとこのこ', 'otokonoko', 'boy'),
('N5', '大人', 'おとな', 'otona', 'adult'),
('N5', '一昨日', 'おととい', 'ototoi', 'day before yesterday'),
('N5', '一昨年', 'おととし', 'ototoshi', 'year before last'),
('N5', 'お父さん', 'おとうさん', 'otousan', 'father'),
('N5', '弟', 'おとうと', 'otouto', 'younger brother'),
('N5', '来月', 'らいげつ', 'raigetsu', 'next month'),
('N5', '来年', 'らいねん', 'rainen', 'next year'),
('N5', '来週', 'らいしゅう', 'raishuu', 'next week'),
('N5', 'ラジオ', 'らじお', 'rajiio', 'radio'),
('N5', '零', 'れい', 'rei', 'zero'),
('N5', '冷蔵庫', 'れいぞうこ', 'reizouko', 'refrigerator'),
('N5', '練習', 'れんしゅう', 'renshuu', 'practice'),
('N5', '六', 'ろく', 'roku', 'six'),
('N5', '廊下', 'ろうか', 'rouka', 'corridor'),
('N5', '旅行', 'りょこう', 'ryokou', 'travel'),
('N5', '料理', 'りょうり', 'ryouri', 'cuisine'),
('N5', '両親', 'りょうしん', 'ryoushin', 'parents'),
('N5', '留学生', 'りゅうがくせい', 'ryuugakusei', 'exchange student'),
('N5', '財布', 'さいふ', 'saifu', 'wallet'),
('N5', '魚', 'さかな', 'sakana', 'fish'),
('N5', '先', 'さき', 'saki', 'previous'),
('N5', '作文', 'さくぶん', 'sakubun', 'writing'),
('N5', '三', 'さん', 'san', 'three'),
('N5', '散歩', 'さんぽ', 'sanpo', 'walk'),
('N5', '再来年', 'さらいねん', 'sarainen', 'year after next'),
('N5', '砂糖', 'さとう', 'satou', 'sugar'),
('N5', '背', 'せ', 'se', 'height'),
('N5', '背広', 'せびろ', 'sebiro', 'business suit'),
('N5', '生徒', 'せいと', 'seito', 'student'),
('N5', '石鹼', 'せっけん', 'sekken', 'soap'),
('N5', '千', 'せん', 'sen', 'thousand'),
('N5', '先月', 'せんげつ', 'sengetsu', 'last month'),
('N5', '先生', 'せんせい', 'sensei', 'teacher'),
('N5', '先週', 'せんしゅう', 'senshuu', 'last week'),
('N5', '洗濯', 'せんたく', 'sentaku', 'laundry'),
('N5', '写真', 'しゃしん', 'shashin', 'photograph'),
('N5', '四', 'し', 'shi', 'four'),
('N5', '七', 'しち', 'shichi', 'seven'),
('N5', '仕事', 'しごと', 'shigoto', 'work'),
('N5', '新聞', 'しんぶん', 'shinbun', 'newspaper'),
('N5', '塩', 'しお', 'shio', 'salt'),
('N5', '白', 'しろ', 'shiro', 'white'),
('N5', '下', 'した', 'shita', 'down'),
('N5', '質問', 'しつもん', 'shitsumon', 'question'),
('N5', '食堂', 'しょくどう', 'shokudou', 'cafeteria'),
('N5', '醬油', 'しょうゆ', 'shouyu', 'soy sauce'),
('N5', '宿題', 'しゅくだい', 'shukudai', 'homework'),
('N5', 'そば', 'そば', 'soba', 'noodle'),
('N5', '空', 'そら', 'sora', 'sky'),
('N5', '外', 'そと', 'soto', 'outside'),
('N5', '水曜日', 'すいようび', 'suiyoubi', 'Wednesday'),
('N5', '好き', 'すき', 'suki', 'like'),
('N5', 'ストーブ', 'すとーぶ', 'sutoobu', 'stove'),
('N5', 'たばこ', 'たばこ', 'tabako', 'tobacco'),
('N5', '大切', 'たいせつ', 'taisetsu', 'important'),
('N5', '大使館', 'たいしかん', 'taishikan', 'embassy'),
('N5', '沢山', 'たくさん', 'takusan', 'many'),
('N5', '卵', 'たまご', 'tamago', 'eggs'),
('N5', '誕生日', 'たんじょうび', 'tanjoubi', 'birthday'),
('N5', '縦', 'たて', 'tate', 'length'),
('N5', '建物', 'たてもの', 'tatemono', 'building'),
('N5', '手', 'て', 'te', 'hand'),
('N5', '手紙', 'てがみ', 'tegami', 'letter'),
('N5', '天気', 'てんき', 'tenki', 'weather'),
('N5', '戸', 'と', 'to', 'Japanese style door'),
('N5', '時計', 'とけい', 'tokei', 'watch'),
('N5', '時', 'とき', 'toki', 'time'),
('N5', '所', 'ところ', 'tokoro', 'place'),
('N5', '友達', 'ともだち', 'tomodachi', 'friend'),
('N5', '隣', 'となり', 'tonari', 'next door to'),
('N5', '十日', 'とおか', 'tooka', 'tenth day of the month'),
('N5', '鳥', 'とり', 'tori', 'bird'),
('N5', '鶏肉', 'とりにく', 'toriniku', 'chicken meat'),
('N5', '年', 'とし', 'toshi', 'year'),
('N5', '図書館', 'としょかん', 'toshokan', 'library'),
('N5', '次', 'つぎ', 'tsugi', 'next'),
('N5', '一日', 'ついたち', 'tsuitachi', 'first day of the month'),
('N5', '机', 'つくえ', 'tsukue', 'desk'),
('N5', '上', 'うえ', 'ue', 'above'),
('N5', '海', 'うみ', 'umi', 'sea'),
('N5', '後ろ', 'うしろ', 'ushiro', 'behind'),
('N5', '歌', 'うた', 'uta', 'song'),
('N5', '上着', 'うわぎ', 'uwagi', 'coat'),
('N5', 'ワイシャツ', 'わい しゃつ', 'wai shatsu', 'shirt'),
('N5', '山', 'やま', 'yama', 'mountain'),
('N5', '八百屋', 'やおや', 'yaoya', 'greengrocer'),
('N5', '野菜', 'やさい', 'yasai', 'vegetable'),
('N5', '休み', 'やすみ', 'yasumi', 'holiday'),
('N5', '八つ', 'やっつ', 'yattsu', 'eight'),
('N5', '四日', 'よっか', 'yokka', 'fourth day of the month'),
('N5', '横', 'よこ', 'yoko', 'beside'),
('N5', '夜', 'よる', 'yoru', 'night'),
('N5', '四つ', 'よつ', 'yotsu', 'four'),
('N5', '洋服', 'ようふく', 'youfuku', 'western clothes'),
('N5', '八日', 'ようか', 'youka', 'eighth day of the month'),
('N5', '雪', 'ゆき', 'yuki', 'snow'),
('N5', '昨夜', 'ゆうべ', 'yuube', 'last night'),
('N5', '郵便局', 'ゆうびんきょく', 'yuubinkyoku', 'post office'),
('N5', '夕方', 'ゆうがた', 'yuugata', 'evening'),
('N5', '夕飯', 'ゆうはん', 'yuuhan', 'dinner'),
('N5', '有名', 'ゆうめい', 'yuumei', 'famous'),
('N5', '雑誌', 'ざっし', 'zasshi', 'magazine'),
('N5', '全部', 'ぜんぶ', 'zenbu', 'all'),
('N5', 'ズボン', 'ずぼん', 'zubon', 'pants');

COMMIT;
