-- Insert JLPT N5 verbs into the words table
INSERT INTO words (word_level, japanese, kana, romaji, english) VALUES
('N5', '浴びる', 'あびる', 'abiru', 'to bathe'),
('N5', '上げる', 'あげる', 'ageru', 'to raise'),
('N5', '開ける', 'あける', 'akeru', 'to open'),
('N5', '開く', 'あく', 'aku', 'to open'),
('N5', '洗う', 'あらう', 'arau', 'to wash'),
('N5', 'ある', 'ある', 'aru', 'to be'),
('N5', '歩く', 'あるく', 'aruku', 'to walk'),
('N5', '遊ぶ', 'あそぶ', 'asobu', 'to play'),
('N5', '会う', 'あう', 'au', 'to meet'),
('N5', '勉強', 'べんきょう', 'benkyou', 'to study'),
('N5', '違う', 'ちがう', 'chigau', 'to differ'),
('N5', '出す', 'だす', 'dasu', 'to take out'),
('N5', '出かける', 'でかける', 'dekakeru', 'to go out'),
('N5', '電話', 'でんわ', 'denwa', 'to telephone'),
('N5', '出る', 'でる', 'deru', 'to leave'),
('N5', '吹く', 'ふく', 'fuku', 'to blow'),
('N5', '降る', 'ふる', 'furu', 'to fall'),
('N5', '入る', 'はいる', 'hairu', 'to enter'),
('N5', '始まる', 'はじまる', 'hajimaru', 'to begin'),
('N5', '履く', 'はく', 'haku', 'to wear'),
('N5', '話す', 'はなす', 'hanasu', 'to speak'),
('N5', '晴れる', 'はれる', 'hareru', 'to be sunny'),
('N5', '貼る', 'はる', 'haru', 'to stick'),
('N5', '走る', 'はしる', 'hashiru', 'to run'),
('N5', '働く', 'はたらく', 'hataraku', 'to work'),
('N5', '引く', 'ひく', 'hiku', 'to pull'),
('N5', '弾く', 'ひく', 'hiku', 'to play'),
('N5', '行く', 'いく', 'iku', 'to go'),
('N5', '入れる', 'いれる', 'ireru', 'to put in'),
('N5', '要る', 'いる', 'iru', 'to be needed'),
('N5', '居る', 'いる', 'iru', 'to be'),
('N5', '言う', 'いう', 'iu', 'to say'),
('N5', '帰る', 'かえる', 'kaeru', 'to go back'),
('N5', '返す', 'かえす', 'kaesu', 'to return something'),
('N5', '掛かる', 'かかる', 'kakaru', 'to take'),
('N5', '掛ける', 'かける', 'kakeru', 'to hang up'),
('N5', '書く', 'かく', 'kaku', 'to write'),
('N5', '借りる', 'かりる', 'kariru', 'to borrow'),
('N5', '貸す', 'かす', 'kasu', 'to lend'),
('N5', '買う', 'かう', 'kau', 'to buy'),
('N5', '結婚', 'けっこん', 'kekkon', 'to marry'),
('N5', '消す', 'けす', 'kesu', 'to erase'),
('N5', '消える', 'きえる', 'kieru', 'to disappear'),
('N5', '聞く', 'きく', 'kiku', 'to hear'),
('N5', '切る', 'きる', 'kiru', 'to cut'),
('N5', '着る', 'きる', 'kiru', 'to wear'),
('N5', '困る', 'こまる', 'komaru', 'to be troubled'),
('N5', '答える', 'こたえる', 'kotaeru', 'to answer'),
('N5', '曇る', 'くもる', 'kumoru', 'to become cloudy'),
('N5', '来る', 'くる', 'kuru', 'to come'),
('N5', '曲がる', 'まがる', 'magaru', 'to turn'),
('N5', '待つ', 'まつ', 'matsu', 'to wait'),
('N5', '磨く', 'みがく', 'migaku', 'to polish'),
('N5', '見る', 'みる', 'miru', 'to see'),
('N5', '見せる', 'みせる', 'miseru', 'to show'),
('N5', '持つ', 'もつ', 'motsu', 'to hold'),
('N5', '鳴く', 'なく', 'naku', 'to chirp'),
('N5', '無くす', 'なくす', 'nakusu', 'to lose'),
('N5', '並べる', 'ならべる', 'naraberu', 'to line up'),
('N5', '並ぶ', 'ならぶ', 'narabu', 'to stand in a line'),
('N5', '習う', 'ならう', 'narau', 'to learn'),
('N5', '寝る', 'ねる', 'neru', 'to sleep'),
('N5', '登る', 'のぼる', 'noboru', 'to climb'),
('N5', '飲む', 'のむ', 'nomu', 'to drink'),
('N5', '乗る', 'のる', 'noru', 'to get on'),
('N5', '脱ぐ', 'ぬぐ', 'nugu', 'to take off'),
('N5', '覚える', 'おぼえる', 'oboeru', 'to remember'),
('N5', '起きる', 'おきる', 'okiru', 'to get up'),
('N5', '置く', 'おく', 'oku', 'to put'),
('N5', '降りる', 'おりる', 'oriru', 'to get off'),
('N5', '教える', 'おしえる', 'oshieru', 'to teach'),
('N5', '押す', 'おす', 'osu', 'to push'),
('N5', '終わる', 'おわる', 'owaru', 'to finish'),
('N5', '泳ぐ', 'およぐ', 'oyogu', 'to swim'),
('N5', '練習', 'れんしゅう', 'renshuu', 'to practice'),
('N5', '旅行', 'りょこう', 'ryokou', 'to travel'),
('N5', '料理', 'りょうり', 'ryouri', 'to cook'),
('N5', '咲く', 'さく', 'saku', 'to bloom'),
('N5', '散歩', 'さんぽ', 'sanpo', 'to walk'),
('N5', '差す', 'さす', 'sasu', 'to stretch out'),
('N5', '洗濯', 'せんたく', 'sentaku', 'to do laundry'),
('N5', '仕事', 'しごと', 'shigoto', 'to work'),
('N5', '閉まる', 'しまる', 'shimaru', 'to close'),
('N5', '閉める', 'しめる', 'shimeru', 'to close'),
('N5', '締める', 'しめる', 'shimeru', 'to tie'),
('N5', '死ぬ', 'しぬ', 'shinu', 'to die'),
('N5', '知る', 'しる', 'shiru', 'to know'),
('N5', '掃除', 'そうじ', 'souji', 'to clean'),
('N5', '住む', 'すむ', 'sumu', 'to live'),
('N5', '吸う', 'すう', 'suu', 'to smoke'),
('N5', '座る', 'すわる', 'suwaru', 'to sit'),
('N5', '食べる', 'たべる', 'taberu', 'to eat'),
('N5', '頼む', 'たのむ', 'tanomu', 'to ask'),
('N5', '立つ', 'たつ', 'tatsu', 'to stand')
('N5', 'テスト', 'てすと', 'tesuto', 'to test'),
('N5', '飛ぶ', 'とぶ', 'tobu', 'to fly'),
('N5', '止まる', 'とまる', 'tomaru', 'to stop');
