-- JLPT N5 Adjective Import Script

BEGIN TRANSACTION;

INSERT INTO words (word_level, japanese, kana, romaji, english) VALUES
('N5', '危ない', 'あぶない', 'abunai', 'dangerous'),
('N5', '赤い', 'あかい', 'akai', 'red'),
('N5', '明るい', 'あかるい', 'akarui', 'bright'),
('N5', '甘い', 'あまい', 'amai', 'sweet'),
('N5', '青い', 'あおい', 'aoi', 'blue'),
('N5', '新しい', 'あたらしい', 'atarashii', 'new'),
('N5', '暖かい', 'あたたかい', 'atatakai', 'warm'),
('N5', '厚い', 'あつい', 'atsui', 'thick'),
('N5', '暑い', 'あつい', 'atsui', 'hot'),
('N5', '熱い', 'あつい', 'atsui', 'hot'),
('N5', '小さい', 'ちいさい', 'chiisai', 'small'),
('N5', '近い', 'ちかい', 'chikai', 'near'),
('N5', '大丈夫', 'だいじょうぶ', 'daijoubu', 'OK'),
('N5', '大好き', 'だいすき', 'daisuki', 'like'),
('N5', '古い', 'ふるい', 'furui', 'old'),
('N5', '太い', 'ふとい', 'futoi', 'fat'),
('N5', '元気', 'げんき', 'genki', 'lively'),
('N5', '速い', 'はやい', 'hayai', 'fast'),
('N5', '早い', 'はやい', 'hayai', 'early'),
('N5', '低い', 'ひくい', 'hikui', 'short'),
('N5', '暇', 'ひま', 'hima', 'free time'),
('N5', '広い', 'ひろい', 'hiroi', 'wide'),
('N5', '欲しい', 'ほしい', 'hoshii', 'want'),
('N5', '細い', 'ほそい', 'hosoi', 'thin'),
('N5', '忙しい', 'いそがしい', 'isogashii', 'busy'),
('N5', '痛い', 'いたい', 'itai', 'painful'),
('N5', '嫌', 'いや', 'iya', 'unpleasant'),
('N5', '丈夫', 'じょうぶ', 'joubu', 'strong'),
('N5', '辛い', 'からい', 'karai', 'spicy'),
('N5', '軽い', 'かるい', 'karui', 'light'),
('N5', '可愛い', 'かわいい', 'kawaii', 'cute'),
('N5', '黄色い', 'きいろい', 'kiiroi', 'yellow'),
('N5', '嫌い', 'きらい', 'kirai', 'hate'),
('N5', '綺麗', 'きれい', 'kirei', 'beautiful'),
('N5', '汚い', 'きたない', 'kitanai', 'dirty'),
('N5', '暗い', 'くらい', 'kurai', 'dark'),
('N5', '黒い', 'くろい', 'kuroi', 'black'),
('N5', '丸い', 'まるい', 'marui', 'round'),
('N5', '不味い', 'まずい', 'mazui', 'unpleasant'),
('N5', '短い', 'みじかい', 'mijikai', 'short'),
('N5', '難しい', 'むずかしい', 'muzukashii', 'difficult'),
('N5', '長い', 'ながい', 'nagai', 'long'),
('N5', '賑やか', 'にぎやか', 'nigiyaka', 'busy'),
('N5', '温い', 'ぬるい', 'nurui', 'lukewarm'),
('N5', '美味しい', 'おいしい', 'oishii', 'delicious'),
('N5', '重い', 'おもい', 'omoi', 'heavy'),
('N5', '面白い', 'おもしろい', 'omoshiroi', 'interesting'),
('N5', '多い', 'おおい', 'ooi', 'many'),
('N5', '大きい', 'おおきい', 'ookii', 'big'),
('N5', '遅い', 'おそい', 'osoi', 'slow'),
('N5', '立派', 'りっぱ', 'rippa', 'splendid'),
('N5', '寒い', 'さむい', 'samui', 'cold'),
('N5', '狭い', 'せまい', 'semai', 'narrow'),
('N5', '白い', 'しろい', 'shiroi', 'white'),
('N5', '静か', 'しずか', 'shizuka', 'quiet'),
('N5', '好き', 'すき', 'suki', 'like'),
('N5', '少ない', 'すくない', 'sukunai', 'few'),
('N5', '爽やか', 'すずしい', 'suzushii', 'refreshing'),
('N5', '大切', 'たいせつ', 'taisetsu', 'important'),
('N5', '高い', 'たかい', 'takai', 'high'),
('N5', '沢山', 'たくさん', 'takusan', 'many'),
('N5', '楽しい', 'たのしい', 'tanoshii', 'fun'),
('N5', '遠い', 'とおい', 'tooi', 'far'),
('N5', '詰まらない', 'つまらない', 'tsumaranai', 'boring'),
('N5', '冷たい', 'つめたい', 'tsumetai', 'cold to the touch'),
('N5', '強い', 'つよい', 'tsuyoi', 'strong'),
('N5', '煩い', 'うるさい', 'urusai', 'noisy'),
('N5', '薄い', 'うすい', 'usui', 'thin'),
('N5', '若い', 'わかい', 'wakai', 'young'),
('N5', '悪い', 'わるい', 'warui', 'bad'),
('N5', '易しい', 'やさしい', 'yasashii', 'easy'),
('N5', '安い', 'やすい', 'yasui', 'cheap'),
('N5', '良い', 'よい', 'yoi', 'good'),
('N5', '弱い', 'よわい', 'yowai', 'weak'),
('N5', '有名', 'ゆうめい', 'yuumei', 'famous');

COMMIT;