-- JLPT N5 Katakana Import Script

BEGIN TRANSACTION;

INSERT INTO words (word_level, japanese, kana, romaji, english) VALUES
('N5', 'アパート', 'あぱーと', 'apaato', 'apartment'),
('N5', 'バス', 'ばす', 'basu', 'bus'),
('N5', 'バター', 'ばたー', 'bataa', 'butter'),
('N5', 'ベッド', 'べっど', 'beddo', 'bed'),
('N5', 'ボールペン', 'ぼーるぺん', 'boorupen', 'ball-point pen'),
('N5', 'ボタン', 'ぼたん', 'botan', 'button'),
('N5', 'デパート', 'でぱーと', 'depaato', 'department store'),
('N5', 'ドア', 'どあ', 'doa', 'door'),
('N5', 'エレベーター', 'えれべーたー', 'erebeetaa', 'elevator'),
('N5', 'フィルム', 'ふぃるむ', 'firumu', 'film'),
('N5', 'フォーク', 'ふぉーく', 'fooku', 'fork'),
('N5', 'ギター', 'ぎたー', 'gitaa', 'guitar'),
('N5', 'グラム', 'ぐらむ', 'guramu', 'gram'),
('N5', 'ハンカチ', 'はんかち', 'hankachi', 'handkerchief'),
('N5', 'ホテル', 'ほてる', 'hoteru', 'hotel'),
('N5', 'カメラ', 'かめら', 'kamera', 'camera'),
('N5', 'カップ', 'かっぷ', 'kappu', 'cup'),
('N5', 'カレー', 'かれー', 'karee', 'curry'),
('N5', 'カレンダー', 'かれんだー', 'karendaa', 'calendar'),
('N5', 'キログラム', 'きろぐらむ', 'kiro guramu', 'kilogram'),
('N5', 'キロメートル', 'きろめーとる', 'kiro meetoru', 'kilometer'),
('N5', 'コーヒー', 'こーひー', 'koohii', 'coffee'),
('N5', 'コート', 'こーと', 'kooto', 'coat'),
('N5', 'コピー', 'こぴー', 'kopii', 'copy'),
('N5', 'コップ', 'こっぷ', 'koppu', 'glass'),
('N5', 'クラス', 'くらす', 'kurasu', 'class'),
('N5', 'マッチ', 'まっち', 'macchi', 'match'),
('N5', 'メートル', 'めーとる', 'meetoru', 'meter'),
('N5', 'ナイフ', 'ないふ', 'naifu', 'knife'),
('N5', 'ネクタイ', 'ねくたい', 'nekutai', 'necktie'),
('N5', 'ノート', 'のーと', 'nooto', 'notebook'),
('N5', 'ニュース', 'にゅーす', 'nyuusu', 'news'),
('N5', 'パーティー', 'ぱーてぃー', 'paatii', 'party'),
('N5', 'パン', 'ぱん', 'pan', 'bread'),
('N5', 'ページ', 'ぺーじ', 'peeji', 'page'),
('N5', 'ペン', 'ぺん', 'pen', 'pen'),
('N5', 'ペット', 'ぺっと', 'petto', 'pet'),
('N5', 'ポケット', 'ぽけっと', 'poketto', 'pocket'),
('N5', 'ポスト', 'ぽすと', 'posuto', 'post'),
('N5', 'プール', 'ぷーる', 'puuru', 'swimming pool'),
('N5', 'ラジオ', 'らじお', 'rajio', 'radio'),
('N5', 'レコード', 'れこーど', 'rekoodo', 'record'),
('N5', 'レストラン', 'れすとらん', 'resutoran', 'restaurant'),
('N5', 'セーター', 'せーたー', 'seetaa', 'sweater'),
('N5', 'シャワー', 'しゃわー', 'shawaa', 'shower'),
('N5', 'シャープペンシル', 'しゃーぷぺんしる', 'shaapupenshiru', 'propelling pencil'),
('N5', 'スカート', 'すかーと', 'sukaato', 'skirt'),
('N5', 'スポーツ', 'すぽーつ', 'supootsu', 'sport'),
('N5', 'スプーン', 'すぷーん', 'supuun', 'spoon'),
('N5', 'スリッパ', 'すりっぱ', 'surippa', 'slipper'),
('N5', 'ストーブ', 'すとーぶ', 'sutobu', 'stove'),
('N5', 'タクシー', 'たくしー', 'takushii', 'taxi'),
('N5', 'テーブル', 'てーぶる', 'teeburu', 'table'),
('N5', 'テープ', 'てーぷ', 'teepu', 'tape'),
('N5', 'テープレコーダー', 'てーぷれこーだー', 'teepu rekoodaa', 'tape recorder'),
('N5', 'テレビ', 'てれび', 'terebi', 'television'),
('N5', 'テスト', 'てすと', 'tesuto', 'test'),
('N5', 'トイレ', 'といれ', 'toire', 'toilet'),
('N5', 'ワイシャツ', 'わいしゃつ', 'waishatsu', 'shirt'),
('N5', 'ゼロ', 'ぜろ', 'zero', 'zero');

COMMIT;
