ktor:
    deployment:
        port: 8080
        watch:
            - classes
            - resources
    application:
        modules:
            - com.pohlondrej.langportal.backend.ApplicationKt.module
    database:
        file: words.db